[project]
name = "holobench"
version = "1.20.0"

authors = [{ name = "Austin Gregg-Smith", email = "blooop@gmail.com" }]
description = "A package for benchmarking the performance of arbitrary functions"
readme = "README.md"

#incompatible with setuptools
requires-python = ">= 3.10"

dependencies = [
  "holoviews>=1.15,<=1.18.3",
  "numpy>=1.0,<=1.26.4",
  "param>=1.13.0,<=2.1.0",
  "hvplot>=0.8,<=0.10.0",
  "matplotlib>=3.6.3,<=3.9.0",
  "panel>=1.3.6,<=1.4.3",
  "diskcache>=5.6,<=5.6.3",
  "optuna>=3.2,<=3.6.1",
  "xarray>=2023.7,<=2024.5.0",
  "plotly>=5.15,<=5.22.0",
  "sortedcontainers>=2.4,<=2.4",
  "pandas>=2.0,<=2.2.2",
  "strenum>=0.4.0,<=0.4.15",
  "scikit-learn>=1.2,<=1.5.0",
  "str2bool>=1.1,<=1.1",
  "scoop>=0.7.0,<=0.7.2.0",
  "moviepy>=1.0.3,<=1.0.3",
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = ">=3.10"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"
[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.pypi-dependencies]
holobench = { path = ".", editable = true }

[project.optional-dependencies]
test = [
  "black>=23,<=24.4.2",
  "pylint>=2.17.7,<=3.1.1",
  "pytest-cov>=4.1,<=5.0.0",
  "pytest>=7.4,<=8.2.0",
  "hypothesis>=6.82,<=6.100.5",
  "ruff>=0.3,<=0.4.3",
  "coverage>=7.2.7,<=7.5.1",
]

[project.urls]
Repository = "https://github.com/dyson-ai/bencher"
Home = "https://github.com/dyson-ai/bencher"
Documentation = "https://bencher.readthedocs.io/en/latest/"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# Environments
[tool.pixi.environments]
default = {features = ["test"], solve-group = "default" }
py310 = ["py310","test"]
py311 = ["py311","test"]


[tool.pixi.feature.test.tasks]
format = "black ."
check-clean-workspace = "git diff --exit-code"
ruff-lint = "ruff check . --fix"
pylint = "echo 'running pylint...'; pylint --version && pylint $(git ls-files '*.py')"
lint = { depends_on = ["ruff-lint","check-clean-workspace", "pylint"] }
style = { depends_on = ["format","lint"]}
test = "pytest"
coverage = "coverage run -m pytest; coverage xml -o coverage.xml"
coverage-report = "coverage report -m"
ci-no-cover = { depends_on = ["style", "test"] }
ci = { depends_on = ["style", "coverage", "coverage-report"] }
update-lock-push = "pixi install; git commit -a -m'update pixi.lock';git push"


[tool.setuptools.packages.find]
include = ["python_template"]

[tool.pylint]
extension-pkg-whitelist = ["numpy", "scipy"]
jobs = 16                                    #detect number of cores

[tool.pylint.'MESSAGES CONTROL']
disable = "C,logging-fstring-interpolation,line-too-long,fixme,broad-exception-caught,missing-module-docstring,too-many-instance-attributes,too-few-public-methods,too-many-arguments,too-many-locals,too-many-branches,too-many-statements,use-dict-literal,cyclic-import,duplicate-code,too-many-public-methods,too-many-nested-blocks"
enable = "no-else-return,consider-using-in"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100 # Same as Black.

target-version = "py310"

[tool.ruff.lint]
# Never enforce `E501` (line length violations).
#"F841" will auto remove unused variables which is annoying during development, pylint catches this anyway
ignore = ["E501", "E902", "F841"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]


[tool.coverage.run]
omit = ["*/test/*", "__init__.py"]

[tool.coverage.report]
exclude_also = [
  "def __repr__",
  "if False:",
  "if 0:",
  "raise AssertionError",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "pass",
  "(_):",
]
